### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by CDAGaming** [SantaGitHub/Svarka#1]
@SantaGitHub 
`
C:\Users\tonyg\Desktop\Svarka\src\main\java\org\bukkit\craftbukkit\map\CraftMapCanvas.java:104: error: unclosed character literal
                if (ch == '┬º') {
                             ^
C:\Users\tonyg\Desktop\Svarka\src\main\java\org\bukkit\craftbukkit\util\CraftChatMessage.java:28: error: unclosed character literal
        LINK_PATTERN = Pattern.compile("((?:(?:https?):\\/\\/)?(?:[-\\w_\\.]{2,}\\.[a-z]{2,4}.*?(?=[\\.\\?!,;:]?(?:[" + String.valueOf('┬º') + " \\n]|$))))");
`

These are the main files with errors but there are other errors within these files

**Comment by SantaGitHub** [comment]
Use script Build.bat

**Comment by CDAGaming** [comment]
Will try that

**Comment by CDAGaming** [comment]
`
:Svarka:compileJavaC:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\command\CommandTP.java:95: error: illegal start of expression
                }*/
                 ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\command\CommandTP.java:95: error: illegal start of expression
                }*/
                  ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\command\CommandTP.java:98: error: illegal start of expression
                if ((entity).getBukkitEntity().teleport(entity.getBukkitEntity(), org.bukkit.event.player.PlayerTeleportEvent.TeleportCause.COMMAND)) {
                ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\command\CommandTP.java:98: error: not a statement
                if ((entity).getBukkitEntity().teleport(entity.getBukkitEntity(), org.bukkit.event.player.PlayerTeleportEvent.TeleportCause.COMMAND)) {
                   ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\command\CommandTP.java:98: error: ';' expected
                if ((entity).getBukkitEntity().teleport(entity.getBukkitEntity(), org.bukkit.event.player.PlayerTeleportEvent.TeleportCause.COMMAND)) {
                                                                                                                                                     ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\entity\EntityLivingBase.java:926: error: illegal start of expression
                }*/
                 ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\entity\EntityLivingBase.java:926: error: illegal start of expression
                }*/
                  ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\server\management\PlayerList.java:534: error: unclosed comment
        /*UUID uuid = EntityPlayer.getUUID(profile);
        ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\server\management\PlayerList.java:1342: error: reached end of file while parsing
}
 ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\world\Teleporter.java:86: error: unclosed comment
        /*
        ^
C:\Users\tonyg\Desktop\Svarka\projects\Svarka\src\main\java\net\minecraft\world\Teleporter.java:446: error: reached end of file while parsing
}
 ^
11 errors
 FAILED
`

**Comment by CDAGaming** [comment]
@SantaGitHub

**Comment by SantaGitHub** [comment]
Я сейчас не поддерживаю сварку. 
Собираю своё ядро Crutch. В моем гите

**Comment by SantaGitHub** [comment]
@CDAGaming [link](https://github.com/SantaGitHub/crutch)
