### ISSUE TITLE
Не работает PermissionsEX

### ISSUE THREAD

**Issue by lnik801l** [SantaGitHub/Svarka#2]
Не работает подключение к бд в плагине PermissionsEX. Логи: https://pastebin.com/5xqkjuT1
Версия пермсов 1.23.4

**Comment by SantaGitHub** [comment]
Последнюю версию ядра использовал?

**Comment by lnik801l** [comment]
Да, вчера с Яндекс диска скачивал

**Comment by SantaGitHub** [comment]
зайди в libraries\mysql\mysql-connector-java\5.1.14
и проверь полное название файла с его типом. Там была ошибка, два раза .jar.jar указал.
![image](https://user-images.githubusercontent.com/11507166/35500217-c137fb40-04e6-11e8-8bb6-c2076c9a2d34.png)

**Comment by lnik801l** [comment]
Все работает. Спасибо :)
